// Generated by scripts/export_typescript_contracts.py. Do not edit.
import type { FromSchema } from "json-schema-to-ts";

export const IdentityResponseSchema = {
  "additionalProperties": false,
  "properties": {
    "can_manage_connections": {
      "default": false,
      "title": "Can Manage Connections",
      "type": "boolean"
    },
    "user_id": {
      "title": "User Id",
      "type": "string"
    },
    "sites": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "id": {
            "title": "Id",
            "type": "string"
          },
          "user_id": {
            "title": "User Id",
            "type": "string"
          },
          "name": {
            "title": "Name",
            "type": "string"
          },
          "timezone": {
            "title": "Timezone",
            "type": "string"
          },
          "latitude": {
            "anyOf": [
              {
                "maximum": 90,
                "minimum": -90,
                "type": "number"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Latitude"
          },
          "longitude": {
            "anyOf": [
              {
                "maximum": 180,
                "minimum": -180,
                "type": "number"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Longitude"
          }
        },
        "required": [
          "id",
          "user_id",
          "name",
          "timezone"
        ],
        "title": "Site",
        "type": "object"
      },
      "title": "Sites",
      "type": "array"
    },
    "assets": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "id": {
            "title": "Id",
            "type": "string"
          },
          "site_id": {
            "title": "Site Id",
            "type": "string"
          },
          "name": {
            "title": "Name",
            "type": "string"
          },
          "kind": {
            "title": "Kind",
            "type": "string"
          },
          "parent_id": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Parent Id"
          },
          "account_ids": {
            "items": {
              "type": "string"
            },
            "title": "Account Ids",
            "type": "array"
          }
        },
        "required": [
          "id",
          "site_id",
          "name",
          "kind",
          "parent_id",
          "account_ids"
        ],
        "title": "IdentityAsset",
        "type": "object"
      },
      "title": "Assets",
      "type": "array"
    }
  },
  "required": [
    "user_id",
    "sites",
    "assets"
  ],
  "title": "IdentityResponse",
  "type": "object"
} as const;
export type IdentityResponse = FromSchema<typeof IdentityResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const ConnectionSetupsResponseSchema = {
  "additionalProperties": false,
  "properties": {
    "setups": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "toolkit_id": {
            "title": "Toolkit Id",
            "type": "string"
          },
          "provider": {
            "const": "octopus",
            "title": "Provider",
            "type": "string"
          },
          "description": {
            "title": "Description",
            "type": "string"
          },
          "enabled": {
            "title": "Enabled",
            "type": "boolean"
          },
          "unavailable_reason": {
            "anyOf": [
              {
                "enum": [
                  "management_key_required",
                  "storage_unavailable"
                ],
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Unavailable Reason"
          },
          "fields": {
            "items": {
              "additionalProperties": false,
              "properties": {
                "name": {
                  "enum": [
                    "credential",
                    "mpan",
                    "serial_number"
                  ],
                  "title": "Name",
                  "type": "string"
                },
                "label": {
                  "title": "Label",
                  "type": "string"
                },
                "secret": {
                  "title": "Secret",
                  "type": "boolean"
                },
                "min_length": {
                  "title": "Min Length",
                  "type": "integer"
                },
                "max_length": {
                  "title": "Max Length",
                  "type": "integer"
                },
                "pattern": {
                  "anyOf": [
                    {
                      "type": "string"
                    },
                    {
                      "type": "null"
                    }
                  ],
                  "default": null,
                  "title": "Pattern"
                }
              },
              "required": [
                "name",
                "label",
                "secret",
                "min_length",
                "max_length"
              ],
              "title": "ConnectionField",
              "type": "object"
            },
            "title": "Fields",
            "type": "array"
          }
        },
        "required": [
          "toolkit_id",
          "provider",
          "description",
          "enabled",
          "fields"
        ],
        "title": "ConnectionSetup",
        "type": "object"
      },
      "title": "Setups",
      "type": "array"
    }
  },
  "required": [
    "setups"
  ],
  "title": "ConnectionSetupsResponse",
  "type": "object"
} as const;
export type ConnectionSetupsResponse = FromSchema<typeof ConnectionSetupsResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const OctopusConnectionRequestSchema = {
  "additionalProperties": false,
  "properties": {
    "provider": {
      "const": "octopus",
      "title": "Provider",
      "type": "string"
    },
    "credential": {
      "maxLength": 4096,
      "minLength": 1,
      "title": "Credential",
      "type": "string"
    },
    "mpan": {
      "pattern": "^[0-9]{13}$",
      "title": "Mpan",
      "type": "string"
    },
    "serial_number": {
      "maxLength": 120,
      "minLength": 1,
      "pattern": "^[A-Za-z0-9._~-]+$",
      "title": "Serial Number",
      "type": "string"
    }
  },
  "required": [
    "provider",
    "credential",
    "mpan",
    "serial_number"
  ],
  "title": "OctopusConnectionRequest",
  "type": "object"
} as const;
export type OctopusConnectionRequest = FromSchema<typeof OctopusConnectionRequestSchema, { keepDefaultedPropertiesOptional: true }>;

export const SessionCreateSchema = {
  "additionalProperties": false,
  "properties": {
    "site_id": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Site Id"
    },
    "resume_job_id": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Resume Job Id"
    }
  },
  "title": "_SessionCreate",
  "type": "object"
} as const;
export type SessionCreate = FromSchema<typeof SessionCreateSchema, { keepDefaultedPropertiesOptional: true }>;

export const SearchRequestSchema = {
  "additionalProperties": false,
  "properties": {
    "query": {
      "maxLength": 2000,
      "minLength": 1,
      "title": "Query",
      "type": "string"
    },
    "limit": {
      "default": 5,
      "maximum": 10,
      "minimum": 1,
      "title": "Limit",
      "type": "integer"
    }
  },
  "required": [
    "query"
  ],
  "title": "_SearchRequest",
  "type": "object"
} as const;
export type SearchRequest = FromSchema<typeof SearchRequestSchema, { keepDefaultedPropertiesOptional: true }>;

export const ExecuteRequestSchema = {
  "additionalProperties": false,
  "properties": {
    "tool": {
      "maxLength": 256,
      "minLength": 1,
      "title": "Tool",
      "type": "string"
    },
    "arguments": {
      "additionalProperties": true,
      "title": "Arguments",
      "type": "object"
    },
    "account_id": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Account Id"
    },
    "persist": {
      "default": false,
      "title": "Persist",
      "type": "boolean"
    },
    "input_artifacts": {
      "items": {
        "type": "string"
      },
      "maxItems": 10,
      "title": "Input Artifacts",
      "type": "array"
    }
  },
  "required": [
    "tool"
  ],
  "title": "_ExecuteRequest",
  "type": "object"
} as const;
export type ExecuteRequest = FromSchema<typeof ExecuteRequestSchema, { keepDefaultedPropertiesOptional: true }>;

export const CapabilityRequestSchema = {
  "additionalProperties": false,
  "properties": {
    "capability": {
      "maxLength": 100,
      "minLength": 1,
      "title": "Capability",
      "type": "string"
    },
    "arguments": {
      "additionalProperties": true,
      "title": "Arguments",
      "type": "object"
    },
    "asset_id": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Asset Id"
    },
    "account_id": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Account Id"
    },
    "kind": {
      "anyOf": [
        {
          "enum": [
            "metered",
            "calculated",
            "estimated",
            "simulated",
            "forecast"
          ],
          "title": "DataKind",
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null
    },
    "unit": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Unit"
    },
    "resolution": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Resolution"
    },
    "tool": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Tool"
    },
    "max_age_seconds": {
      "anyOf": [
        {
          "maximum": 86400,
          "minimum": 1,
          "type": "integer"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Max Age Seconds"
    },
    "input_artifacts": {
      "items": {
        "type": "string"
      },
      "maxItems": 10,
      "title": "Input Artifacts",
      "type": "array"
    }
  },
  "required": [
    "capability"
  ],
  "title": "CapabilityRequest",
  "type": "object"
} as const;
export type CapabilityRequest = FromSchema<typeof CapabilityRequestSchema, { keepDefaultedPropertiesOptional: true }>;

export const CapabilityExecutionRequestSchema = {
  "additionalProperties": false,
  "properties": {
    "capability": {
      "maxLength": 100,
      "minLength": 1,
      "title": "Capability",
      "type": "string"
    },
    "arguments": {
      "additionalProperties": true,
      "title": "Arguments",
      "type": "object"
    },
    "asset_id": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Asset Id"
    },
    "account_id": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Account Id"
    },
    "kind": {
      "anyOf": [
        {
          "enum": [
            "metered",
            "calculated",
            "estimated",
            "simulated",
            "forecast"
          ],
          "title": "DataKind",
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null
    },
    "unit": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Unit"
    },
    "resolution": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Resolution"
    },
    "tool": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Tool"
    },
    "max_age_seconds": {
      "anyOf": [
        {
          "maximum": 86400,
          "minimum": 1,
          "type": "integer"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Max Age Seconds"
    },
    "input_artifacts": {
      "items": {
        "type": "string"
      },
      "maxItems": 10,
      "title": "Input Artifacts",
      "type": "array"
    },
    "persist": {
      "default": false,
      "title": "Persist",
      "type": "boolean"
    }
  },
  "required": [
    "capability"
  ],
  "title": "_CapabilityExecutionRequest",
  "type": "object"
} as const;
export type CapabilityExecutionRequest = FromSchema<typeof CapabilityExecutionRequestSchema, { keepDefaultedPropertiesOptional: true }>;

export const JobRequestSchema = {
  "additionalProperties": false,
  "properties": {
    "operation": {
      "title": "Operation",
      "type": "string"
    },
    "job_id": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Job Id"
    },
    "simulation": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Simulation"
    },
    "arguments": {
      "additionalProperties": true,
      "title": "Arguments",
      "type": "object"
    }
  },
  "required": [
    "operation"
  ],
  "title": "_JobRequest",
  "type": "object"
} as const;
export type JobRequest = FromSchema<typeof JobRequestSchema, { keepDefaultedPropertiesOptional: true }>;

export const SkillExecutionRequestSchema = {
  "additionalProperties": false,
  "properties": {
    "skill_id": {
      "maxLength": 128,
      "minLength": 1,
      "title": "Skill Id",
      "type": "string"
    },
    "parameters": {
      "additionalProperties": true,
      "title": "Parameters",
      "type": "object"
    }
  },
  "required": [
    "skill_id"
  ],
  "title": "_SkillExecutionRequest",
  "type": "object"
} as const;
export type SkillExecutionRequest = FromSchema<typeof SkillExecutionRequestSchema, { keepDefaultedPropertiesOptional: true }>;

export const WorkflowResponseSchema = {
  "oneOf": [
    {
      "type": "object",
      "properties": {
        "ok": {
          "const": true
        }
      },
      "required": [
        "ok"
      ],
      "additionalProperties": true
    },
    {
      "type": "object",
      "properties": {
        "ok": {
          "const": false
        },
        "error": {
          "type": "object",
          "properties": {
            "code": {
              "type": "string"
            },
            "message": {
              "type": "string"
            },
            "retryable": {
              "type": "boolean"
            }
          },
          "required": [
            "code",
            "message"
          ],
          "additionalProperties": true
        }
      },
      "required": [
        "ok",
        "error"
      ],
      "additionalProperties": true
    }
  ]
} as const;
export type WorkflowResponse = FromSchema<typeof WorkflowResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const EnergyResultSchema = {
  "additionalProperties": false,
  "properties": {
    "data": {
      "title": "Data"
    },
    "kind": {
      "enum": [
        "metered",
        "calculated",
        "estimated",
        "simulated",
        "forecast"
      ],
      "title": "DataKind",
      "type": "string"
    },
    "unit": {
      "title": "Unit",
      "type": "string"
    },
    "source": {
      "title": "Source",
      "type": "string"
    },
    "timezone": {
      "default": "UTC",
      "title": "Timezone",
      "type": "string"
    },
    "resolution": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Resolution"
    },
    "provider": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Provider"
    },
    "site_id": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Site Id"
    },
    "asset_id": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Asset Id"
    },
    "time_start": {
      "anyOf": [
        {
          "format": "date-time",
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Time Start"
    },
    "time_end": {
      "anyOf": [
        {
          "format": "date-time",
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Time End"
    },
    "quantity_shape": {
      "anyOf": [
        {
          "enum": [
            "interval",
            "instantaneous",
            "counter"
          ],
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Quantity Shape"
    },
    "original_unit": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Original Unit"
    },
    "field_units": {
      "additionalProperties": {
        "type": "string"
      },
      "title": "Field Units",
      "type": "object"
    },
    "retrieved_at": {
      "format": "date-time",
      "title": "Retrieved At",
      "type": "string"
    },
    "assumptions": {
      "items": {
        "type": "string"
      },
      "title": "Assumptions",
      "type": "array"
    },
    "warnings": {
      "items": {
        "type": "string"
      },
      "title": "Warnings",
      "type": "array"
    },
    "quality": {
      "default": "unknown",
      "title": "Quality",
      "type": "string"
    },
    "provenance": {
      "items": {
        "additionalProperties": true,
        "type": "object"
      },
      "title": "Provenance",
      "type": "array"
    }
  },
  "required": [
    "data",
    "kind",
    "unit",
    "source"
  ],
  "title": "EnergyResult",
  "type": "object"
} as const;
export type EnergyResult = FromSchema<typeof EnergyResultSchema, { keepDefaultedPropertiesOptional: true }>;

export const ToolkitSchema = {
  "additionalProperties": false,
  "properties": {
    "id": {
      "title": "Id",
      "type": "string"
    },
    "name": {
      "title": "Name",
      "type": "string"
    },
    "description": {
      "title": "Description",
      "type": "string"
    },
    "runtime": {
      "enum": [
        "http",
        "python",
        "native",
        "executable",
        "mcp-local",
        "mcp-remote"
      ],
      "title": "Runtime",
      "type": "string"
    },
    "status": {
      "enum": [
        "stable",
        "experimental",
        "requires credentials",
        "unavailable"
      ],
      "title": "Status",
      "type": "string"
    },
    "auth_required": {
      "default": false,
      "title": "Auth Required",
      "type": "boolean"
    },
    "docs_url": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Docs Url"
    },
    "version": {
      "default": "1.0.0",
      "title": "Version",
      "type": "string"
    },
    "categories": {
      "items": {
        "type": "string"
      },
      "title": "Categories",
      "type": "array"
    }
  },
  "required": [
    "id",
    "name",
    "description",
    "runtime",
    "status"
  ],
  "title": "Toolkit",
  "type": "object"
} as const;
export type Toolkit = FromSchema<typeof ToolkitSchema, { keepDefaultedPropertiesOptional: true }>;

export const ToolkitsResponseSchema = {
  "type": "object",
  "properties": {
    "toolkits": {
      "type": "array",
      "items": {
        "additionalProperties": false,
        "properties": {
          "id": {
            "title": "Id",
            "type": "string"
          },
          "name": {
            "title": "Name",
            "type": "string"
          },
          "description": {
            "title": "Description",
            "type": "string"
          },
          "runtime": {
            "enum": [
              "http",
              "python",
              "native",
              "executable",
              "mcp-local",
              "mcp-remote"
            ],
            "title": "Runtime",
            "type": "string"
          },
          "status": {
            "enum": [
              "stable",
              "experimental",
              "requires credentials",
              "unavailable"
            ],
            "title": "Status",
            "type": "string"
          },
          "auth_required": {
            "default": false,
            "title": "Auth Required",
            "type": "boolean"
          },
          "docs_url": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Docs Url"
          },
          "version": {
            "default": "1.0.0",
            "title": "Version",
            "type": "string"
          },
          "categories": {
            "items": {
              "type": "string"
            },
            "title": "Categories",
            "type": "array"
          }
        },
        "required": [
          "id",
          "name",
          "description",
          "runtime",
          "status"
        ],
        "title": "Toolkit",
        "type": "object"
      }
    }
  },
  "required": [
    "toolkits"
  ],
  "additionalProperties": true
} as const;
export type ToolkitsResponse = FromSchema<typeof ToolkitsResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const SessionResponseSchema = {
  "type": "object",
  "properties": {
    "session_id": {
      "type": "string"
    },
    "site_id": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    }
  },
  "required": [
    "session_id",
    "site_id"
  ],
  "additionalProperties": true
} as const;
export type SessionResponse = FromSchema<typeof SessionResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const SearchResponseSchema = {
  "type": "object",
  "properties": {
    "tools": {
      "type": "array",
      "items": {
        "additionalProperties": true,
        "properties": {
          "name": {
            "title": "Name",
            "type": "string"
          },
          "toolkit": {
            "title": "Toolkit",
            "type": "string"
          },
          "resource_scope": {
            "default": "unclassified",
            "enum": [
              "unclassified",
              "operator",
              "public",
              "account",
              "session"
            ],
            "title": "Resource Scope",
            "type": "string"
          },
          "description": {
            "title": "Description",
            "type": "string"
          },
          "input_schema": {
            "additionalProperties": true,
            "title": "Input Schema",
            "type": "object"
          },
          "capabilities": {
            "items": {
              "type": "string"
            },
            "title": "Capabilities",
            "type": "array"
          },
          "actions": {
            "items": {
              "enum": [
                "read-only",
                "calculation",
                "simulation",
                "external-data",
                "configuration-write",
                "physical-control",
                "safety-critical"
              ],
              "title": "Action",
              "type": "string"
            },
            "title": "Actions",
            "type": "array",
            "uniqueItems": true
          },
          "idempotent": {
            "default": true,
            "title": "Idempotent",
            "type": "boolean"
          },
          "version": {
            "default": "1.0.0",
            "title": "Version",
            "type": "string"
          },
          "reviewed": {
            "default": true,
            "title": "Reviewed",
            "type": "boolean"
          },
          "result_kind": {
            "anyOf": [
              {
                "enum": [
                  "metered",
                  "calculated",
                  "estimated",
                  "simulated",
                  "forecast"
                ],
                "title": "DataKind",
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null
          },
          "result_unit": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Result Unit"
          },
          "dependencies": {
            "items": {
              "type": "string"
            },
            "title": "Dependencies",
            "type": "array"
          },
          "connection_available": {
            "type": "boolean"
          }
        },
        "required": [
          "name",
          "toolkit",
          "description",
          "input_schema",
          "capabilities"
        ],
        "title": "Tool",
        "type": "object"
      }
    }
  },
  "required": [
    "tools"
  ],
  "additionalProperties": true
} as const;
export type SearchResponse = FromSchema<typeof SearchResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const ExecutionResponseSchema = {
  "oneOf": [
    {
      "type": "object",
      "properties": {
        "ok": {
          "const": true
        },
        "execution_id": {
          "type": "string"
        },
        "result": {
          "additionalProperties": false,
          "properties": {
            "data": {
              "title": "Data"
            },
            "kind": {
              "enum": [
                "metered",
                "calculated",
                "estimated",
                "simulated",
                "forecast"
              ],
              "title": "DataKind",
              "type": "string"
            },
            "unit": {
              "title": "Unit",
              "type": "string"
            },
            "source": {
              "title": "Source",
              "type": "string"
            },
            "timezone": {
              "default": "UTC",
              "title": "Timezone",
              "type": "string"
            },
            "resolution": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "default": null,
              "title": "Resolution"
            },
            "provider": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "default": null,
              "title": "Provider"
            },
            "site_id": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "default": null,
              "title": "Site Id"
            },
            "asset_id": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "default": null,
              "title": "Asset Id"
            },
            "time_start": {
              "anyOf": [
                {
                  "format": "date-time",
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "default": null,
              "title": "Time Start"
            },
            "time_end": {
              "anyOf": [
                {
                  "format": "date-time",
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "default": null,
              "title": "Time End"
            },
            "quantity_shape": {
              "anyOf": [
                {
                  "enum": [
                    "interval",
                    "instantaneous",
                    "counter"
                  ],
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "default": null,
              "title": "Quantity Shape"
            },
            "original_unit": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "default": null,
              "title": "Original Unit"
            },
            "field_units": {
              "additionalProperties": {
                "type": "string"
              },
              "title": "Field Units",
              "type": "object"
            },
            "retrieved_at": {
              "format": "date-time",
              "title": "Retrieved At",
              "type": "string"
            },
            "assumptions": {
              "items": {
                "type": "string"
              },
              "title": "Assumptions",
              "type": "array"
            },
            "warnings": {
              "items": {
                "type": "string"
              },
              "title": "Warnings",
              "type": "array"
            },
            "quality": {
              "default": "unknown",
              "title": "Quality",
              "type": "string"
            },
            "provenance": {
              "items": {
                "additionalProperties": true,
                "type": "object"
              },
              "title": "Provenance",
              "type": "array"
            }
          },
          "required": [
            "data",
            "kind",
            "unit",
            "source"
          ],
          "title": "EnergyResult",
          "type": "object"
        }
      },
      "required": [
        "ok",
        "execution_id",
        "result"
      ],
      "additionalProperties": true
    },
    {
      "type": "object",
      "properties": {
        "ok": {
          "const": false
        },
        "execution_id": {
          "type": "string"
        },
        "error": {
          "type": "object",
          "properties": {
            "code": {
              "type": "string"
            },
            "message": {
              "type": "string"
            },
            "retryable": {
              "type": "boolean"
            }
          },
          "required": [
            "code",
            "message"
          ],
          "additionalProperties": true
        },
        "resolution": {
          "type": "object",
          "additionalProperties": true
        }
      },
      "required": [
        "ok",
        "error"
      ],
      "additionalProperties": true
    }
  ]
} as const;
export type ExecutionResponse = FromSchema<typeof ExecutionResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const ResolutionResponseSchema = {
  "type": "object",
  "properties": {
    "capability": {
      "type": "string"
    },
    "candidates": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": true
      }
    },
    "selected": {
      "anyOf": [
        {
          "type": "object",
          "additionalProperties": true
        },
        {
          "type": "null"
        }
      ]
    },
    "status": {
      "enum": [
        "resolved",
        "ambiguous",
        "unavailable"
      ]
    },
    "note": {
      "type": "string"
    }
  },
  "required": [
    "capability",
    "candidates",
    "selected",
    "status",
    "note"
  ],
  "additionalProperties": true
} as const;
export type ResolutionResponse = FromSchema<typeof ResolutionResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const ConnectionCreatedResponseSchema = {
  "type": "object",
  "properties": {
    "ok": {
      "const": true
    },
    "account": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "toolkit": {
          "type": "string"
        },
        "site_id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "enabled": {
          "type": "boolean"
        },
        "auth_scheme": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "verified": {
          "type": "boolean"
        }
      },
      "required": [
        "id",
        "toolkit",
        "site_id",
        "enabled",
        "auth_scheme",
        "state",
        "verified"
      ],
      "additionalProperties": true
    },
    "health": {
      "type": "object",
      "properties": {
        "connection_id": {
          "type": "string"
        },
        "provider": {
          "const": "octopus"
        },
        "status": {
          "const": "healthy"
        },
        "checked_at": {
          "type": "string"
        },
        "probe": {
          "const": "provider-read"
        },
        "message": {
          "type": "string"
        }
      },
      "required": [
        "connection_id",
        "provider",
        "status",
        "checked_at",
        "probe",
        "message"
      ],
      "additionalProperties": true
    }
  },
  "required": [
    "ok",
    "account",
    "health"
  ],
  "additionalProperties": true
} as const;
export type ConnectionCreatedResponse = FromSchema<typeof ConnectionCreatedResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const ConnectionVerificationResponseSchema = {
  "type": "object",
  "properties": {
    "ok": {
      "const": true
    },
    "account": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "toolkit": {
          "type": "string"
        },
        "site_id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "enabled": {
          "type": "boolean"
        },
        "auth_scheme": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "verified": {
          "type": "boolean"
        }
      },
      "required": [
        "id",
        "toolkit",
        "site_id",
        "enabled",
        "auth_scheme",
        "state",
        "verified"
      ],
      "additionalProperties": true
    },
    "health": {
      "type": "object",
      "properties": {
        "connection_id": {
          "type": "string"
        },
        "provider": {
          "const": "octopus"
        },
        "status": {
          "enum": [
            "healthy",
            "unhealthy"
          ]
        },
        "checked_at": {
          "type": "string"
        },
        "probe": {
          "const": "provider-read"
        },
        "message": {
          "type": "string"
        }
      },
      "required": [
        "connection_id",
        "provider",
        "status",
        "checked_at",
        "probe",
        "message"
      ],
      "additionalProperties": true
    }
  },
  "required": [
    "ok",
    "account",
    "health"
  ],
  "additionalProperties": true
} as const;
export type ConnectionVerificationResponse = FromSchema<typeof ConnectionVerificationResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const ConnectionDisconnectedResponseSchema = {
  "type": "object",
  "properties": {
    "ok": {
      "const": true
    },
    "account": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "toolkit": {
          "type": "string"
        },
        "site_id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "enabled": {
          "type": "boolean"
        },
        "auth_scheme": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "verified": {
          "type": "boolean"
        }
      },
      "required": [
        "id",
        "toolkit",
        "site_id",
        "enabled",
        "auth_scheme",
        "state",
        "verified"
      ],
      "additionalProperties": true
    }
  },
  "required": [
    "ok",
    "account"
  ],
  "additionalProperties": true
} as const;
export type ConnectionDisconnectedResponse = FromSchema<typeof ConnectionDisconnectedResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const ConnectionsResponseSchema = {
  "type": "object",
  "properties": {
    "connections": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "toolkit": {
            "type": "string"
          },
          "site_id": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "enabled": {
            "type": "boolean"
          },
          "auth_scheme": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "verified": {
            "type": "boolean"
          }
        },
        "required": [
          "id",
          "toolkit",
          "site_id",
          "enabled",
          "auth_scheme",
          "state",
          "verified"
        ],
        "additionalProperties": true
      }
    }
  },
  "required": [
    "connections"
  ],
  "additionalProperties": true
} as const;
export type ConnectionsResponse = FromSchema<typeof ConnectionsResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const ArtifactsResponseSchema = {
  "type": "object",
  "properties": {
    "artifacts": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": true
      }
    }
  },
  "required": [
    "artifacts"
  ],
  "additionalProperties": true
} as const;
export type ArtifactsResponse = FromSchema<typeof ArtifactsResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const SkillsResponseSchema = {
  "type": "object",
  "properties": {
    "skills": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "intent": {
            "type": "string"
          },
          "capabilities": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "sequence": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "supporting_tools": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "pitfalls": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "id",
          "intent",
          "capabilities",
          "sequence",
          "pitfalls"
        ],
        "additionalProperties": true
      }
    }
  },
  "required": [
    "skills"
  ],
  "additionalProperties": true
} as const;
export type SkillsResponse = FromSchema<typeof SkillsResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const JobResponseSchema = {
  "oneOf": [
    {
      "type": "object",
      "properties": {
        "ok": {
          "const": true
        }
      },
      "required": [
        "ok"
      ],
      "additionalProperties": true
    },
    {
      "type": "object",
      "properties": {
        "ok": {
          "const": false
        },
        "error": {
          "type": "object",
          "properties": {
            "code": {
              "type": "string"
            },
            "message": {
              "type": "string"
            },
            "retryable": {
              "type": "boolean"
            }
          },
          "required": [
            "code",
            "message"
          ],
          "additionalProperties": true
        }
      },
      "required": [
        "ok",
        "error"
      ],
      "additionalProperties": true
    }
  ]
} as const;
export type JobResponse = FromSchema<typeof JobResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const DeleteSessionResponseSchema = {
  "type": "object",
  "properties": {
    "deleted": {
      "const": true
    },
    "session_id": {
      "type": "string"
    }
  },
  "required": [
    "deleted",
    "session_id"
  ],
  "additionalProperties": true
} as const;
export type DeleteSessionResponse = FromSchema<typeof DeleteSessionResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const DeleteArtifactResponseSchema = {
  "type": "object",
  "properties": {
    "deleted": {
      "const": true
    },
    "artifact_id": {
      "type": "string"
    }
  },
  "required": [
    "deleted",
    "artifact_id"
  ],
  "additionalProperties": true
} as const;
export type DeleteArtifactResponse = FromSchema<typeof DeleteArtifactResponseSchema, { keepDefaultedPropertiesOptional: true }>;
