// Generated by scripts/export_typescript_contracts.py. Do not edit.
import type { FromSchema } from "json-schema-to-ts";

export const IdentityResponseSchema = {
  "additionalProperties": false,
  "properties": {
    "can_manage_connections": {
      "default": false,
      "title": "Can Manage Connections",
      "type": "boolean"
    },
    "can_manage_workspace": {
      "default": false,
      "title": "Can Manage Workspace",
      "type": "boolean"
    },
    "workspace": {
      "anyOf": [
        {
          "additionalProperties": false,
          "properties": {
            "id": {
              "title": "Id",
              "type": "string"
            },
            "user_id": {
              "title": "User Id",
              "type": "string"
            },
            "name": {
              "title": "Name",
              "type": "string"
            },
            "mode": {
              "enum": [
                "operator",
                "managed"
              ],
              "title": "Mode",
              "type": "string"
            }
          },
          "required": [
            "id",
            "user_id",
            "name",
            "mode"
          ],
          "title": "WorkspaceDetails",
          "type": "object"
        },
        {
          "type": "null"
        }
      ],
      "default": null
    },
    "user_id": {
      "title": "User Id",
      "type": "string"
    },
    "sites": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "id": {
            "title": "Id",
            "type": "string"
          },
          "user_id": {
            "title": "User Id",
            "type": "string"
          },
          "name": {
            "title": "Name",
            "type": "string"
          },
          "timezone": {
            "title": "Timezone",
            "type": "string"
          },
          "latitude": {
            "anyOf": [
              {
                "maximum": 90,
                "minimum": -90,
                "type": "number"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Latitude"
          },
          "longitude": {
            "anyOf": [
              {
                "maximum": 180,
                "minimum": -180,
                "type": "number"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Longitude"
          }
        },
        "required": [
          "id",
          "user_id",
          "name",
          "timezone"
        ],
        "title": "Site",
        "type": "object"
      },
      "title": "Sites",
      "type": "array"
    },
    "assets": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "id": {
            "title": "Id",
            "type": "string"
          },
          "site_id": {
            "title": "Site Id",
            "type": "string"
          },
          "name": {
            "title": "Name",
            "type": "string"
          },
          "kind": {
            "title": "Kind",
            "type": "string"
          },
          "parent_id": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Parent Id"
          },
          "account_ids": {
            "items": {
              "type": "string"
            },
            "title": "Account Ids",
            "type": "array"
          }
        },
        "required": [
          "id",
          "site_id",
          "name",
          "kind",
          "parent_id",
          "account_ids"
        ],
        "title": "IdentityAsset",
        "type": "object"
      },
      "title": "Assets",
      "type": "array"
    }
  },
  "required": [
    "user_id",
    "sites",
    "assets"
  ],
  "title": "IdentityResponse",
  "type": "object"
} as const;
export type IdentityResponse = FromSchema<typeof IdentityResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const ExecutionLogResponseSchema = {
  "additionalProperties": false,
  "properties": {
    "entries": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "execution_id": {
            "maxLength": 256,
            "minLength": 1,
            "title": "Execution Id",
            "type": "string"
          },
          "user_id": {
            "maxLength": 256,
            "minLength": 1,
            "title": "User Id",
            "type": "string"
          },
          "workspace_id": {
            "anyOf": [
              {
                "maxLength": 256,
                "minLength": 1,
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Workspace Id"
          },
          "key_id": {
            "anyOf": [
              {
                "maxLength": 256,
                "minLength": 1,
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Key Id"
          },
          "session_id": {
            "maxLength": 256,
            "minLength": 1,
            "title": "Session Id",
            "type": "string"
          },
          "site_id": {
            "anyOf": [
              {
                "maxLength": 256,
                "minLength": 1,
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Site Id"
          },
          "account_id": {
            "anyOf": [
              {
                "maxLength": 256,
                "minLength": 1,
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Account Id"
          },
          "access_mode": {
            "enum": [
              "local",
              "hosted"
            ],
            "title": "Access Mode",
            "type": "string"
          },
          "recorded_at": {
            "format": "date-time",
            "title": "Recorded At",
            "type": "string"
          },
          "tool": {
            "maxLength": 256,
            "minLength": 1,
            "title": "Tool",
            "type": "string"
          },
          "duration_ms": {
            "minimum": 0,
            "title": "Duration Ms",
            "type": "number"
          },
          "outcome": {
            "discriminator": {
              "mapping": {
                "failure": "#/$defs/ExecutionFailure",
                "success": "#/$defs/ExecutionSuccess"
              },
              "propertyName": "kind"
            },
            "oneOf": [
              {
                "additionalProperties": false,
                "properties": {
                  "kind": {
                    "const": "success",
                    "title": "Kind",
                    "type": "string"
                  },
                  "data_kind": {
                    "anyOf": [
                      {
                        "enum": [
                          "metered",
                          "calculated",
                          "estimated",
                          "simulated",
                          "forecast"
                        ],
                        "title": "DataKind",
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ],
                    "default": null
                  }
                },
                "required": [
                  "kind"
                ],
                "title": "ExecutionSuccess",
                "type": "object"
              },
              {
                "additionalProperties": false,
                "properties": {
                  "kind": {
                    "const": "failure",
                    "title": "Kind",
                    "type": "string"
                  },
                  "error_code": {
                    "maxLength": 256,
                    "minLength": 1,
                    "title": "Error Code",
                    "type": "string"
                  }
                },
                "required": [
                  "kind",
                  "error_code"
                ],
                "title": "ExecutionFailure",
                "type": "object"
              }
            ],
            "title": "Outcome"
          },
          "sequence": {
            "exclusiveMinimum": 0,
            "title": "Sequence",
            "type": "integer"
          }
        },
        "required": [
          "execution_id",
          "user_id",
          "workspace_id",
          "key_id",
          "session_id",
          "site_id",
          "account_id",
          "access_mode",
          "recorded_at",
          "tool",
          "duration_ms",
          "outcome",
          "sequence"
        ],
        "title": "ExecutionLogRecord",
        "type": "object"
      },
      "maxItems": 100,
      "title": "Entries",
      "type": "array"
    },
    "next_before": {
      "anyOf": [
        {
          "exclusiveMinimum": 0,
          "type": "integer"
        },
        {
          "type": "null"
        }
      ],
      "title": "Next Before"
    },
    "retention_limit": {
      "maximum": 2000,
      "minimum": 1,
      "title": "Retention Limit",
      "type": "integer"
    },
    "recording_status": {
      "enum": [
        "ok",
        "unavailable"
      ],
      "title": "Recording Status",
      "type": "string"
    }
  },
  "required": [
    "entries",
    "next_before",
    "retention_limit",
    "recording_status"
  ],
  "title": "ExecutionLogPage",
  "type": "object"
} as const;
export type ExecutionLogResponse = FromSchema<typeof ExecutionLogResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const ExecutionLogQuerySchema = {
  "additionalProperties": false,
  "properties": {
    "limit": {
      "default": 50,
      "maximum": 100,
      "minimum": 1,
      "title": "Limit",
      "type": "integer"
    },
    "before": {
      "anyOf": [
        {
          "exclusiveMinimum": 0,
          "maximum": 9007199254740991,
          "type": "integer"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Before"
    }
  },
  "title": "ExecutionLogQuery",
  "type": "object"
} as const;
export type ExecutionLogQuery = FromSchema<typeof ExecutionLogQuerySchema, { keepDefaultedPropertiesOptional: true }>;

export const JobHistoryResponseSchema = {
  "additionalProperties": false,
  "properties": {
    "jobs": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "job_id": {
            "pattern": "^[a-f0-9]{32}$",
            "title": "Job Id",
            "type": "string"
          },
          "user_id": {
            "maxLength": 256,
            "minLength": 1,
            "title": "User Id",
            "type": "string"
          },
          "session_id": {
            "maxLength": 256,
            "minLength": 1,
            "title": "Session Id",
            "type": "string"
          },
          "workspace_id": {
            "anyOf": [
              {
                "maxLength": 256,
                "minLength": 1,
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Workspace Id"
          },
          "site_id": {
            "anyOf": [
              {
                "maxLength": 256,
                "minLength": 1,
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Site Id"
          },
          "access_mode": {
            "enum": [
              "local",
              "hosted"
            ],
            "title": "Access Mode",
            "type": "string"
          },
          "operation": {
            "description": "Numerical operations that may run in the isolated worker.",
            "enum": [
              "heat_loss",
              "power_flow",
              "battery",
              "solar",
              "network_power_flow",
              "network_dispatch"
            ],
            "title": "SimulationOperation",
            "type": "string"
          },
          "status": {
            "description": "Persistent lifecycle states for a job.",
            "enum": [
              "pending",
              "running",
              "completed",
              "failed",
              "cancelled",
              "interrupted"
            ],
            "title": "JobStatus",
            "type": "string"
          },
          "created_at": {
            "format": "date-time",
            "title": "Created At",
            "type": "string"
          },
          "started_at": {
            "anyOf": [
              {
                "format": "date-time",
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Started At"
          },
          "finished_at": {
            "anyOf": [
              {
                "format": "date-time",
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Finished At"
          },
          "input_bytes": {
            "minimum": 0,
            "title": "Input Bytes",
            "type": "integer"
          },
          "output_bytes": {
            "minimum": 0,
            "title": "Output Bytes",
            "type": "integer"
          },
          "error_code": {
            "anyOf": [
              {
                "pattern": "^[a-z][a-z0-9_]{0,127}$",
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Error Code"
          }
        },
        "required": [
          "job_id",
          "user_id",
          "session_id",
          "workspace_id",
          "site_id",
          "access_mode",
          "operation",
          "status",
          "created_at",
          "started_at",
          "finished_at",
          "input_bytes",
          "output_bytes",
          "error_code"
        ],
        "title": "JobMetadata",
        "type": "object"
      },
      "maxItems": 100,
      "title": "Jobs",
      "type": "array"
    },
    "next_before": {
      "anyOf": [
        {
          "maxLength": 256,
          "minLength": 1,
          "pattern": "^[A-Za-z0-9_-]+$",
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "title": "Next Before"
    }
  },
  "required": [
    "jobs",
    "next_before"
  ],
  "title": "JobMetadataPage",
  "type": "object"
} as const;
export type JobHistoryResponse = FromSchema<typeof JobHistoryResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const JobHistoryQuerySchema = {
  "additionalProperties": false,
  "properties": {
    "limit": {
      "default": 50,
      "maximum": 100,
      "minimum": 1,
      "title": "Limit",
      "type": "integer"
    },
    "before": {
      "anyOf": [
        {
          "maxLength": 256,
          "minLength": 1,
          "pattern": "^[A-Za-z0-9_-]+$",
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Before"
    },
    "status": {
      "anyOf": [
        {
          "enum": [
            "pending",
            "running",
            "completed",
            "failed",
            "cancelled",
            "interrupted"
          ],
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Status"
    }
  },
  "title": "JobListQuery",
  "type": "object"
} as const;
export type JobHistoryQuery = FromSchema<typeof JobHistoryQuerySchema, { keepDefaultedPropertiesOptional: true }>;

export const JobActionQuerySchema = {
  "additionalProperties": false,
  "properties": {
    "operation": {
      "enum": [
        "status",
        "result",
        "cancel",
        "delete"
      ],
      "title": "Operation",
      "type": "string"
    }
  },
  "required": [
    "operation"
  ],
  "title": "JobActionQuery",
  "type": "object"
} as const;
export type JobActionQuery = FromSchema<typeof JobActionQuerySchema, { keepDefaultedPropertiesOptional: true }>;

export const WorkspaceResponseSchema = {
  "type": "object",
  "properties": {
    "workspace": {
      "additionalProperties": false,
      "properties": {
        "id": {
          "title": "Id",
          "type": "string"
        },
        "user_id": {
          "title": "User Id",
          "type": "string"
        },
        "name": {
          "title": "Name",
          "type": "string"
        },
        "mode": {
          "enum": [
            "operator",
            "managed"
          ],
          "title": "Mode",
          "type": "string"
        }
      },
      "required": [
        "id",
        "user_id",
        "name",
        "mode"
      ],
      "title": "WorkspaceDetails",
      "type": "object"
    }
  },
  "required": [
    "workspace"
  ],
  "additionalProperties": true
} as const;
export type WorkspaceResponse = FromSchema<typeof WorkspaceResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const WorkspaceSiteRequestSchema = {
  "additionalProperties": false,
  "properties": {
    "name": {
      "maxLength": 256,
      "minLength": 1,
      "title": "Name",
      "type": "string"
    },
    "timezone": {
      "maxLength": 80,
      "minLength": 1,
      "title": "Timezone",
      "type": "string"
    },
    "latitude": {
      "anyOf": [
        {
          "maximum": 90,
          "minimum": -90,
          "type": "number"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Latitude"
    },
    "longitude": {
      "anyOf": [
        {
          "maximum": 180,
          "minimum": -180,
          "type": "number"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Longitude"
    }
  },
  "required": [
    "name",
    "timezone"
  ],
  "title": "WorkspaceSiteRequest",
  "type": "object"
} as const;
export type WorkspaceSiteRequest = FromSchema<typeof WorkspaceSiteRequestSchema, { keepDefaultedPropertiesOptional: true }>;

export const WorkspaceSiteResponseSchema = {
  "type": "object",
  "properties": {
    "site": {
      "additionalProperties": false,
      "properties": {
        "id": {
          "title": "Id",
          "type": "string"
        },
        "user_id": {
          "title": "User Id",
          "type": "string"
        },
        "name": {
          "title": "Name",
          "type": "string"
        },
        "timezone": {
          "title": "Timezone",
          "type": "string"
        },
        "latitude": {
          "anyOf": [
            {
              "maximum": 90,
              "minimum": -90,
              "type": "number"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Latitude"
        },
        "longitude": {
          "anyOf": [
            {
              "maximum": 180,
              "minimum": -180,
              "type": "number"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Longitude"
        }
      },
      "required": [
        "id",
        "user_id",
        "name",
        "timezone"
      ],
      "title": "Site",
      "type": "object"
    }
  },
  "required": [
    "site"
  ],
  "additionalProperties": true
} as const;
export type WorkspaceSiteResponse = FromSchema<typeof WorkspaceSiteResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const WorkspaceSitesResponseSchema = {
  "type": "object",
  "properties": {
    "sites": {
      "type": "array",
      "items": {
        "additionalProperties": false,
        "properties": {
          "id": {
            "title": "Id",
            "type": "string"
          },
          "user_id": {
            "title": "User Id",
            "type": "string"
          },
          "name": {
            "title": "Name",
            "type": "string"
          },
          "timezone": {
            "title": "Timezone",
            "type": "string"
          },
          "latitude": {
            "anyOf": [
              {
                "maximum": 90,
                "minimum": -90,
                "type": "number"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Latitude"
          },
          "longitude": {
            "anyOf": [
              {
                "maximum": 180,
                "minimum": -180,
                "type": "number"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Longitude"
          }
        },
        "required": [
          "id",
          "user_id",
          "name",
          "timezone"
        ],
        "title": "Site",
        "type": "object"
      }
    }
  },
  "required": [
    "sites"
  ],
  "additionalProperties": true
} as const;
export type WorkspaceSitesResponse = FromSchema<typeof WorkspaceSitesResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const WorkspaceAssetRequestSchema = {
  "additionalProperties": false,
  "properties": {
    "site_id": {
      "maxLength": 256,
      "minLength": 1,
      "title": "Site Id",
      "type": "string"
    },
    "name": {
      "maxLength": 256,
      "minLength": 1,
      "title": "Name",
      "type": "string"
    },
    "kind": {
      "maxLength": 80,
      "minLength": 1,
      "title": "Kind",
      "type": "string"
    },
    "parent_id": {
      "anyOf": [
        {
          "maxLength": 256,
          "minLength": 1,
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Parent Id"
    },
    "account_ids": {
      "items": {
        "type": "string"
      },
      "maxItems": 32,
      "title": "Account Ids",
      "type": "array"
    }
  },
  "required": [
    "site_id",
    "name",
    "kind"
  ],
  "title": "WorkspaceAssetRequest",
  "type": "object"
} as const;
export type WorkspaceAssetRequest = FromSchema<typeof WorkspaceAssetRequestSchema, { keepDefaultedPropertiesOptional: true }>;

export const WorkspaceAssetResponseSchema = {
  "type": "object",
  "properties": {
    "asset": {
      "additionalProperties": false,
      "properties": {
        "id": {
          "title": "Id",
          "type": "string"
        },
        "site_id": {
          "title": "Site Id",
          "type": "string"
        },
        "kind": {
          "maxLength": 80,
          "minLength": 1,
          "title": "Kind",
          "type": "string"
        },
        "name": {
          "title": "Name",
          "type": "string"
        },
        "metadata": {
          "additionalProperties": true,
          "title": "Metadata",
          "type": "object"
        },
        "account_ids": {
          "items": {
            "type": "string"
          },
          "title": "Account Ids",
          "type": "array"
        },
        "parent_id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Parent Id"
        }
      },
      "required": [
        "id",
        "site_id",
        "kind",
        "name"
      ],
      "title": "Asset",
      "type": "object"
    }
  },
  "required": [
    "asset"
  ],
  "additionalProperties": true
} as const;
export type WorkspaceAssetResponse = FromSchema<typeof WorkspaceAssetResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const WorkspaceAssetsResponseSchema = {
  "type": "object",
  "properties": {
    "assets": {
      "type": "array",
      "items": {
        "additionalProperties": false,
        "properties": {
          "id": {
            "title": "Id",
            "type": "string"
          },
          "site_id": {
            "title": "Site Id",
            "type": "string"
          },
          "kind": {
            "maxLength": 80,
            "minLength": 1,
            "title": "Kind",
            "type": "string"
          },
          "name": {
            "title": "Name",
            "type": "string"
          },
          "metadata": {
            "additionalProperties": true,
            "title": "Metadata",
            "type": "object"
          },
          "account_ids": {
            "items": {
              "type": "string"
            },
            "title": "Account Ids",
            "type": "array"
          },
          "parent_id": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Parent Id"
          }
        },
        "required": [
          "id",
          "site_id",
          "kind",
          "name"
        ],
        "title": "Asset",
        "type": "object"
      }
    }
  },
  "required": [
    "assets"
  ],
  "additionalProperties": true
} as const;
export type WorkspaceAssetsResponse = FromSchema<typeof WorkspaceAssetsResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const WorkspaceMapRequestSchema = {
  "additionalProperties": false,
  "properties": {
    "site_id": {
      "maxLength": 256,
      "minLength": 1,
      "title": "Site Id",
      "type": "string"
    }
  },
  "required": [
    "site_id"
  ],
  "title": "WorkspaceMapRequest",
  "type": "object"
} as const;
export type WorkspaceMapRequest = FromSchema<typeof WorkspaceMapRequestSchema, { keepDefaultedPropertiesOptional: true }>;

export const WorkspaceAgentKeyRequestSchema = {
  "additionalProperties": false,
  "properties": {
    "name": {
      "maxLength": 256,
      "minLength": 1,
      "title": "Name",
      "type": "string"
    },
    "site_ids": {
      "items": {
        "type": "string"
      },
      "maxItems": 256,
      "minItems": 1,
      "title": "Site Ids",
      "type": "array"
    }
  },
  "required": [
    "name",
    "site_ids"
  ],
  "title": "WorkspaceAgentKeyRequest",
  "type": "object"
} as const;
export type WorkspaceAgentKeyRequest = FromSchema<typeof WorkspaceAgentKeyRequestSchema, { keepDefaultedPropertiesOptional: true }>;

export const WorkspaceIssuedKeyResponseSchema = {
  "additionalProperties": false,
  "properties": {
    "key": {
      "additionalProperties": false,
      "properties": {
        "id": {
          "maxLength": 256,
          "minLength": 1,
          "title": "Id",
          "type": "string"
        },
        "user_id": {
          "maxLength": 256,
          "minLength": 1,
          "title": "User Id",
          "type": "string"
        },
        "workspace_id": {
          "maxLength": 256,
          "minLength": 1,
          "title": "Workspace Id",
          "type": "string"
        },
        "name": {
          "maxLength": 256,
          "minLength": 1,
          "title": "Name",
          "type": "string"
        },
        "created_at": {
          "format": "date-time",
          "title": "Created At",
          "type": "string"
        },
        "expires_at": {
          "anyOf": [
            {
              "format": "date-time",
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "title": "Expires At"
        },
        "revoked": {
          "title": "Revoked",
          "type": "boolean"
        },
        "token_prefix": {
          "maxLength": 16,
          "minLength": 1,
          "title": "Token Prefix",
          "type": "string"
        },
        "access": {
          "discriminator": {
            "mapping": {
              "agent": "#/$defs/AgentKeyAccess",
              "legacy-agent": "#/$defs/LegacyKeyAccess",
              "manage": "#/$defs/ManageKeyAccess"
            },
            "propertyName": "kind"
          },
          "oneOf": [
            {
              "additionalProperties": false,
              "properties": {
                "kind": {
                  "const": "manage",
                  "default": "manage",
                  "title": "Kind",
                  "type": "string"
                }
              },
              "title": "ManageKeyAccess",
              "type": "object"
            },
            {
              "additionalProperties": false,
              "properties": {
                "kind": {
                  "const": "agent",
                  "default": "agent",
                  "title": "Kind",
                  "type": "string"
                },
                "site_ids": {
                  "items": {
                    "type": "string"
                  },
                  "maxItems": 256,
                  "minItems": 1,
                  "title": "Site Ids",
                  "type": "array"
                }
              },
              "required": [
                "site_ids"
              ],
              "title": "AgentKeyAccess",
              "type": "object"
            },
            {
              "additionalProperties": false,
              "description": "Existing v1 execution keys, never issuable through managed control routes.",
              "properties": {
                "kind": {
                  "const": "legacy-agent",
                  "default": "legacy-agent",
                  "title": "Kind",
                  "type": "string"
                }
              },
              "title": "LegacyKeyAccess",
              "type": "object"
            }
          ],
          "title": "Access"
        }
      },
      "required": [
        "id",
        "user_id",
        "workspace_id",
        "name",
        "created_at",
        "expires_at",
        "revoked",
        "token_prefix",
        "access"
      ],
      "title": "KeyRecord",
      "type": "object"
    },
    "token": {
      "maxLength": 47,
      "minLength": 47,
      "title": "Token",
      "type": "string"
    }
  },
  "required": [
    "key",
    "token"
  ],
  "title": "IssuedKey",
  "type": "object"
} as const;
export type WorkspaceIssuedKeyResponse = FromSchema<typeof WorkspaceIssuedKeyResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const WorkspaceKeysResponseSchema = {
  "type": "object",
  "properties": {
    "keys": {
      "type": "array",
      "items": {
        "additionalProperties": false,
        "properties": {
          "id": {
            "maxLength": 256,
            "minLength": 1,
            "title": "Id",
            "type": "string"
          },
          "user_id": {
            "maxLength": 256,
            "minLength": 1,
            "title": "User Id",
            "type": "string"
          },
          "workspace_id": {
            "maxLength": 256,
            "minLength": 1,
            "title": "Workspace Id",
            "type": "string"
          },
          "name": {
            "maxLength": 256,
            "minLength": 1,
            "title": "Name",
            "type": "string"
          },
          "created_at": {
            "format": "date-time",
            "title": "Created At",
            "type": "string"
          },
          "expires_at": {
            "anyOf": [
              {
                "format": "date-time",
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Expires At"
          },
          "revoked": {
            "title": "Revoked",
            "type": "boolean"
          },
          "token_prefix": {
            "maxLength": 16,
            "minLength": 1,
            "title": "Token Prefix",
            "type": "string"
          },
          "access": {
            "discriminator": {
              "mapping": {
                "agent": "#/$defs/AgentKeyAccess",
                "legacy-agent": "#/$defs/LegacyKeyAccess",
                "manage": "#/$defs/ManageKeyAccess"
              },
              "propertyName": "kind"
            },
            "oneOf": [
              {
                "additionalProperties": false,
                "properties": {
                  "kind": {
                    "const": "manage",
                    "default": "manage",
                    "title": "Kind",
                    "type": "string"
                  }
                },
                "title": "ManageKeyAccess",
                "type": "object"
              },
              {
                "additionalProperties": false,
                "properties": {
                  "kind": {
                    "const": "agent",
                    "default": "agent",
                    "title": "Kind",
                    "type": "string"
                  },
                  "site_ids": {
                    "items": {
                      "type": "string"
                    },
                    "maxItems": 256,
                    "minItems": 1,
                    "title": "Site Ids",
                    "type": "array"
                  }
                },
                "required": [
                  "site_ids"
                ],
                "title": "AgentKeyAccess",
                "type": "object"
              },
              {
                "additionalProperties": false,
                "description": "Existing v1 execution keys, never issuable through managed control routes.",
                "properties": {
                  "kind": {
                    "const": "legacy-agent",
                    "default": "legacy-agent",
                    "title": "Kind",
                    "type": "string"
                  }
                },
                "title": "LegacyKeyAccess",
                "type": "object"
              }
            ],
            "title": "Access"
          }
        },
        "required": [
          "id",
          "user_id",
          "workspace_id",
          "name",
          "created_at",
          "expires_at",
          "revoked",
          "token_prefix",
          "access"
        ],
        "title": "KeyRecord",
        "type": "object"
      }
    }
  },
  "required": [
    "keys"
  ],
  "additionalProperties": true
} as const;
export type WorkspaceKeysResponse = FromSchema<typeof WorkspaceKeysResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const WorkspaceRevokedKeyResponseSchema = {
  "type": "object",
  "properties": {
    "revoked": {
      "const": true
    }
  },
  "required": [
    "revoked"
  ],
  "additionalProperties": true
} as const;
export type WorkspaceRevokedKeyResponse = FromSchema<typeof WorkspaceRevokedKeyResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const WorkspaceMemberRequestSchema = {
  "additionalProperties": false,
  "properties": {
    "user_id": {
      "maxLength": 256,
      "minLength": 1,
      "title": "User Id",
      "type": "string"
    }
  },
  "required": [
    "user_id"
  ],
  "title": "WorkspaceMemberRequest",
  "type": "object"
} as const;
export type WorkspaceMemberRequest = FromSchema<typeof WorkspaceMemberRequestSchema, { keepDefaultedPropertiesOptional: true }>;

export const WorkspaceMemberGrantsSchema = {
  "additionalProperties": false,
  "properties": {
    "site_ids": {
      "items": {
        "type": "string"
      },
      "maxItems": 256,
      "title": "Site Ids",
      "type": "array"
    },
    "connection_ids": {
      "items": {
        "type": "string"
      },
      "maxItems": 256,
      "title": "Connection Ids",
      "type": "array"
    }
  },
  "title": "WorkspaceMemberGrants",
  "type": "object"
} as const;
export type WorkspaceMemberGrants = FromSchema<typeof WorkspaceMemberGrantsSchema, { keepDefaultedPropertiesOptional: true }>;

export const WorkspaceMemberResponseSchema = {
  "type": "object",
  "properties": {
    "member": {
      "additionalProperties": false,
      "properties": {
        "user_id": {
          "maxLength": 256,
          "minLength": 1,
          "title": "User Id",
          "type": "string"
        },
        "workspace_id": {
          "maxLength": 256,
          "minLength": 1,
          "title": "Workspace Id",
          "type": "string"
        },
        "name": {
          "maxLength": 256,
          "minLength": 1,
          "title": "Name",
          "type": "string"
        },
        "role": {
          "const": "member",
          "default": "member",
          "title": "Role",
          "type": "string"
        },
        "grants": {
          "additionalProperties": false,
          "properties": {
            "site_ids": {
              "items": {
                "type": "string"
              },
              "maxItems": 256,
              "title": "Site Ids",
              "type": "array"
            },
            "connection_ids": {
              "items": {
                "type": "string"
              },
              "maxItems": 256,
              "title": "Connection Ids",
              "type": "array"
            }
          },
          "title": "WorkspaceMemberGrants",
          "type": "object"
        }
      },
      "required": [
        "user_id",
        "workspace_id",
        "name"
      ],
      "title": "WorkspaceMember",
      "type": "object"
    }
  },
  "required": [
    "member"
  ],
  "additionalProperties": true
} as const;
export type WorkspaceMemberResponse = FromSchema<typeof WorkspaceMemberResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const WorkspaceMembersResponseSchema = {
  "type": "object",
  "properties": {
    "members": {
      "type": "array",
      "items": {
        "additionalProperties": false,
        "properties": {
          "user_id": {
            "maxLength": 256,
            "minLength": 1,
            "title": "User Id",
            "type": "string"
          },
          "workspace_id": {
            "maxLength": 256,
            "minLength": 1,
            "title": "Workspace Id",
            "type": "string"
          },
          "name": {
            "maxLength": 256,
            "minLength": 1,
            "title": "Name",
            "type": "string"
          },
          "role": {
            "const": "member",
            "default": "member",
            "title": "Role",
            "type": "string"
          },
          "grants": {
            "additionalProperties": false,
            "properties": {
              "site_ids": {
                "items": {
                  "type": "string"
                },
                "maxItems": 256,
                "title": "Site Ids",
                "type": "array"
              },
              "connection_ids": {
                "items": {
                  "type": "string"
                },
                "maxItems": 256,
                "title": "Connection Ids",
                "type": "array"
              }
            },
            "title": "WorkspaceMemberGrants",
            "type": "object"
          }
        },
        "required": [
          "user_id",
          "workspace_id",
          "name"
        ],
        "title": "WorkspaceMember",
        "type": "object"
      }
    }
  },
  "required": [
    "members"
  ],
  "additionalProperties": true
} as const;
export type WorkspaceMembersResponse = FromSchema<typeof WorkspaceMembersResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const WorkspaceMemberRemovedResponseSchema = {
  "type": "object",
  "properties": {
    "removed": {
      "const": true
    }
  },
  "required": [
    "removed"
  ],
  "additionalProperties": true
} as const;
export type WorkspaceMemberRemovedResponse = FromSchema<typeof WorkspaceMemberRemovedResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const WorkspaceOAuthConfigurationsResponseSchema = {
  "additionalProperties": false,
  "properties": {
    "configurations": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "id": {
            "title": "Id",
            "type": "string"
          },
          "name": {
            "title": "Name",
            "type": "string"
          },
          "toolkit": {
            "const": "home-assistant",
            "default": "home-assistant",
            "title": "Toolkit",
            "type": "string"
          },
          "protocol": {
            "const": "home_assistant",
            "default": "home_assistant",
            "title": "Protocol",
            "type": "string"
          },
          "pending_cleanup": {
            "default": 0,
            "minimum": 0,
            "title": "Pending Cleanup",
            "type": "integer"
          }
        },
        "required": [
          "id",
          "name"
        ],
        "title": "WorkspaceOAuthConfiguration",
        "type": "object"
      },
      "title": "Configurations",
      "type": "array"
    }
  },
  "required": [
    "configurations"
  ],
  "title": "WorkspaceOAuthConfigurationsResponse",
  "type": "object"
} as const;
export type WorkspaceOAuthConfigurationsResponse = FromSchema<typeof WorkspaceOAuthConfigurationsResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const WorkspaceHomeAssistantAuthorizationRequestSchema = {
  "additionalProperties": false,
  "properties": {
    "configuration_id": {
      "pattern": "^[a-z0-9][a-z0-9-]{0,63}$",
      "title": "Configuration Id",
      "type": "string"
    },
    "entity_id": {
      "maxLength": 256,
      "minLength": 1,
      "pattern": "^[A-Za-z0-9_.:-]+$",
      "title": "Entity Id",
      "type": "string"
    },
    "mapping": {
      "anyOf": [
        {
          "additionalProperties": false,
          "properties": {
            "telemetry_role": {
              "enum": [
                "consumption_interval",
                "current_power",
                "generation",
                "export",
                "storage_state"
              ],
              "title": "Telemetry Role",
              "type": "string"
            },
            "unit": {
              "enum": [
                "kWh",
                "W",
                "kW",
                "MW",
                "%"
              ],
              "title": "Unit",
              "type": "string"
            },
            "quantity_shape": {
              "enum": [
                "interval",
                "instantaneous"
              ],
              "title": "Quantity Shape",
              "type": "string"
            },
            "measurement_kind": {
              "const": "metered",
              "default": "metered",
              "title": "Measurement Kind",
              "type": "string"
            }
          },
          "required": [
            "telemetry_role",
            "unit",
            "quantity_shape"
          ],
          "title": "ReviewedHomeAssistantMapping",
          "type": "object"
        },
        {
          "type": "null"
        }
      ],
      "default": null
    }
  },
  "required": [
    "configuration_id",
    "entity_id"
  ],
  "title": "WorkspaceHomeAssistantAuthorizationRequest",
  "type": "object"
} as const;
export type WorkspaceHomeAssistantAuthorizationRequest = FromSchema<typeof WorkspaceHomeAssistantAuthorizationRequestSchema, { keepDefaultedPropertiesOptional: true }>;

export const WorkspaceOAuthCompleteRequestSchema = {
  "additionalProperties": false,
  "properties": {
    "configuration_id": {
      "pattern": "^[a-z0-9][a-z0-9-]{0,63}$",
      "title": "Configuration Id",
      "type": "string"
    },
    "state": {
      "maxLength": 512,
      "minLength": 1,
      "title": "State",
      "type": "string"
    },
    "code": {
      "maxLength": 2048,
      "minLength": 1,
      "title": "Code",
      "type": "string"
    }
  },
  "required": [
    "configuration_id",
    "state",
    "code"
  ],
  "title": "WorkspaceOAuthCompleteRequest",
  "type": "object"
} as const;
export type WorkspaceOAuthCompleteRequest = FromSchema<typeof WorkspaceOAuthCompleteRequestSchema, { keepDefaultedPropertiesOptional: true }>;

export const WorkspaceOAuthCleanupRequestSchema = {
  "additionalProperties": false,
  "properties": {
    "configuration_id": {
      "pattern": "^[a-z0-9][a-z0-9-]{0,63}$",
      "title": "Configuration Id",
      "type": "string"
    }
  },
  "required": [
    "configuration_id"
  ],
  "title": "WorkspaceOAuthCleanupRequest",
  "type": "object"
} as const;
export type WorkspaceOAuthCleanupRequest = FromSchema<typeof WorkspaceOAuthCleanupRequestSchema, { keepDefaultedPropertiesOptional: true }>;

export const WorkspaceOAuthCleanupResponseSchema = {
  "additionalProperties": false,
  "properties": {
    "cleanup": {
      "additionalProperties": false,
      "properties": {
        "attempted": {
          "minimum": 0,
          "title": "Attempted",
          "type": "integer"
        },
        "succeeded": {
          "minimum": 0,
          "title": "Succeeded",
          "type": "integer"
        },
        "pending": {
          "minimum": 0,
          "title": "Pending",
          "type": "integer"
        }
      },
      "required": [
        "attempted",
        "succeeded",
        "pending"
      ],
      "title": "WorkspaceOAuthCleanup",
      "type": "object"
    }
  },
  "required": [
    "cleanup"
  ],
  "title": "WorkspaceOAuthCleanupResponse",
  "type": "object"
} as const;
export type WorkspaceOAuthCleanupResponse = FromSchema<typeof WorkspaceOAuthCleanupResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const WorkspaceAuthorizationResponseSchema = {
  "additionalProperties": false,
  "properties": {
    "authorization": {
      "additionalProperties": false,
      "properties": {
        "connection_id": {
          "title": "Connection Id",
          "type": "string"
        },
        "authorization_url": {
          "title": "Authorization Url",
          "type": "string"
        },
        "state": {
          "title": "State",
          "type": "string"
        },
        "expires_at": {
          "format": "date-time",
          "title": "Expires At",
          "type": "string"
        }
      },
      "required": [
        "connection_id",
        "authorization_url",
        "state",
        "expires_at"
      ],
      "title": "WorkspaceAuthorization",
      "type": "object"
    }
  },
  "required": [
    "authorization"
  ],
  "title": "WorkspaceAuthorizationResponse",
  "type": "object"
} as const;
export type WorkspaceAuthorizationResponse = FromSchema<typeof WorkspaceAuthorizationResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const ConnectionSetupsResponseSchema = {
  "additionalProperties": false,
  "properties": {
    "setups": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "toolkit_id": {
            "title": "Toolkit Id",
            "type": "string"
          },
          "provider": {
            "const": "octopus",
            "title": "Provider",
            "type": "string"
          },
          "description": {
            "title": "Description",
            "type": "string"
          },
          "enabled": {
            "title": "Enabled",
            "type": "boolean"
          },
          "unavailable_reason": {
            "anyOf": [
              {
                "enum": [
                  "management_key_required",
                  "storage_unavailable"
                ],
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Unavailable Reason"
          },
          "fields": {
            "items": {
              "additionalProperties": false,
              "properties": {
                "name": {
                  "enum": [
                    "credential",
                    "mpan",
                    "serial_number"
                  ],
                  "title": "Name",
                  "type": "string"
                },
                "label": {
                  "title": "Label",
                  "type": "string"
                },
                "secret": {
                  "title": "Secret",
                  "type": "boolean"
                },
                "min_length": {
                  "title": "Min Length",
                  "type": "integer"
                },
                "max_length": {
                  "title": "Max Length",
                  "type": "integer"
                },
                "pattern": {
                  "anyOf": [
                    {
                      "type": "string"
                    },
                    {
                      "type": "null"
                    }
                  ],
                  "default": null,
                  "title": "Pattern"
                }
              },
              "required": [
                "name",
                "label",
                "secret",
                "min_length",
                "max_length"
              ],
              "title": "ConnectionField",
              "type": "object"
            },
            "title": "Fields",
            "type": "array"
          }
        },
        "required": [
          "toolkit_id",
          "provider",
          "description",
          "enabled",
          "fields"
        ],
        "title": "ConnectionSetup",
        "type": "object"
      },
      "title": "Setups",
      "type": "array"
    }
  },
  "required": [
    "setups"
  ],
  "title": "ConnectionSetupsResponse",
  "type": "object"
} as const;
export type ConnectionSetupsResponse = FromSchema<typeof ConnectionSetupsResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const OctopusConnectionRequestSchema = {
  "additionalProperties": false,
  "properties": {
    "provider": {
      "const": "octopus",
      "title": "Provider",
      "type": "string"
    },
    "credential": {
      "maxLength": 4096,
      "minLength": 1,
      "title": "Credential",
      "type": "string"
    },
    "mpan": {
      "pattern": "^[0-9]{13}$",
      "title": "Mpan",
      "type": "string"
    },
    "serial_number": {
      "maxLength": 120,
      "minLength": 1,
      "pattern": "^[A-Za-z0-9._~-]+$",
      "title": "Serial Number",
      "type": "string"
    }
  },
  "required": [
    "provider",
    "credential",
    "mpan",
    "serial_number"
  ],
  "title": "OctopusConnectionRequest",
  "type": "object"
} as const;
export type OctopusConnectionRequest = FromSchema<typeof OctopusConnectionRequestSchema, { keepDefaultedPropertiesOptional: true }>;

export const SessionCreateSchema = {
  "additionalProperties": false,
  "properties": {
    "site_id": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Site Id"
    },
    "resume_job_id": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Resume Job Id"
    }
  },
  "title": "_SessionCreate",
  "type": "object"
} as const;
export type SessionCreate = FromSchema<typeof SessionCreateSchema, { keepDefaultedPropertiesOptional: true }>;

export const SearchRequestSchema = {
  "additionalProperties": false,
  "properties": {
    "query": {
      "maxLength": 2000,
      "minLength": 1,
      "title": "Query",
      "type": "string"
    },
    "limit": {
      "default": 5,
      "maximum": 10,
      "minimum": 1,
      "title": "Limit",
      "type": "integer"
    }
  },
  "required": [
    "query"
  ],
  "title": "_SearchRequest",
  "type": "object"
} as const;
export type SearchRequest = FromSchema<typeof SearchRequestSchema, { keepDefaultedPropertiesOptional: true }>;

export const ExecuteRequestSchema = {
  "additionalProperties": false,
  "properties": {
    "tool": {
      "maxLength": 256,
      "minLength": 1,
      "title": "Tool",
      "type": "string"
    },
    "arguments": {
      "additionalProperties": true,
      "title": "Arguments",
      "type": "object"
    },
    "account_id": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Account Id"
    },
    "persist": {
      "default": false,
      "title": "Persist",
      "type": "boolean"
    },
    "input_artifacts": {
      "items": {
        "type": "string"
      },
      "maxItems": 10,
      "title": "Input Artifacts",
      "type": "array"
    }
  },
  "required": [
    "tool"
  ],
  "title": "_ExecuteRequest",
  "type": "object"
} as const;
export type ExecuteRequest = FromSchema<typeof ExecuteRequestSchema, { keepDefaultedPropertiesOptional: true }>;

export const CapabilityRequestSchema = {
  "additionalProperties": false,
  "properties": {
    "capability": {
      "maxLength": 100,
      "minLength": 1,
      "title": "Capability",
      "type": "string"
    },
    "arguments": {
      "additionalProperties": true,
      "title": "Arguments",
      "type": "object"
    },
    "asset_id": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Asset Id"
    },
    "account_id": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Account Id"
    },
    "kind": {
      "anyOf": [
        {
          "enum": [
            "metered",
            "calculated",
            "estimated",
            "simulated",
            "forecast"
          ],
          "title": "DataKind",
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null
    },
    "unit": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Unit"
    },
    "resolution": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Resolution"
    },
    "tool": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Tool"
    },
    "max_age_seconds": {
      "anyOf": [
        {
          "maximum": 86400,
          "minimum": 1,
          "type": "integer"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Max Age Seconds"
    },
    "input_artifacts": {
      "items": {
        "type": "string"
      },
      "maxItems": 10,
      "title": "Input Artifacts",
      "type": "array"
    }
  },
  "required": [
    "capability"
  ],
  "title": "CapabilityRequest",
  "type": "object"
} as const;
export type CapabilityRequest = FromSchema<typeof CapabilityRequestSchema, { keepDefaultedPropertiesOptional: true }>;

export const CapabilityExecutionRequestSchema = {
  "additionalProperties": false,
  "properties": {
    "capability": {
      "maxLength": 100,
      "minLength": 1,
      "title": "Capability",
      "type": "string"
    },
    "arguments": {
      "additionalProperties": true,
      "title": "Arguments",
      "type": "object"
    },
    "asset_id": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Asset Id"
    },
    "account_id": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Account Id"
    },
    "kind": {
      "anyOf": [
        {
          "enum": [
            "metered",
            "calculated",
            "estimated",
            "simulated",
            "forecast"
          ],
          "title": "DataKind",
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null
    },
    "unit": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Unit"
    },
    "resolution": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Resolution"
    },
    "tool": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Tool"
    },
    "max_age_seconds": {
      "anyOf": [
        {
          "maximum": 86400,
          "minimum": 1,
          "type": "integer"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Max Age Seconds"
    },
    "input_artifacts": {
      "items": {
        "type": "string"
      },
      "maxItems": 10,
      "title": "Input Artifacts",
      "type": "array"
    },
    "persist": {
      "default": false,
      "title": "Persist",
      "type": "boolean"
    }
  },
  "required": [
    "capability"
  ],
  "title": "_CapabilityExecutionRequest",
  "type": "object"
} as const;
export type CapabilityExecutionRequest = FromSchema<typeof CapabilityExecutionRequestSchema, { keepDefaultedPropertiesOptional: true }>;

export const JobRequestSchema = {
  "additionalProperties": false,
  "properties": {
    "operation": {
      "title": "Operation",
      "type": "string"
    },
    "job_id": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Job Id"
    },
    "simulation": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Simulation"
    },
    "arguments": {
      "additionalProperties": true,
      "title": "Arguments",
      "type": "object"
    }
  },
  "required": [
    "operation"
  ],
  "title": "_JobRequest",
  "type": "object"
} as const;
export type JobRequest = FromSchema<typeof JobRequestSchema, { keepDefaultedPropertiesOptional: true }>;

export const SkillExecutionRequestSchema = {
  "additionalProperties": false,
  "properties": {
    "skill_id": {
      "maxLength": 128,
      "minLength": 1,
      "title": "Skill Id",
      "type": "string"
    },
    "parameters": {
      "additionalProperties": true,
      "title": "Parameters",
      "type": "object"
    }
  },
  "required": [
    "skill_id"
  ],
  "title": "_SkillExecutionRequest",
  "type": "object"
} as const;
export type SkillExecutionRequest = FromSchema<typeof SkillExecutionRequestSchema, { keepDefaultedPropertiesOptional: true }>;

export const WorkflowResponseSchema = {
  "oneOf": [
    {
      "type": "object",
      "properties": {
        "ok": {
          "const": true
        }
      },
      "required": [
        "ok"
      ],
      "additionalProperties": true
    },
    {
      "type": "object",
      "properties": {
        "ok": {
          "const": false
        },
        "error": {
          "type": "object",
          "properties": {
            "code": {
              "type": "string"
            },
            "message": {
              "type": "string"
            },
            "retryable": {
              "type": "boolean"
            }
          },
          "required": [
            "code",
            "message"
          ],
          "additionalProperties": true
        }
      },
      "required": [
        "ok",
        "error"
      ],
      "additionalProperties": true
    }
  ]
} as const;
export type WorkflowResponse = FromSchema<typeof WorkflowResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const EnergyResultSchema = {
  "additionalProperties": false,
  "properties": {
    "data": {
      "title": "Data"
    },
    "kind": {
      "enum": [
        "metered",
        "calculated",
        "estimated",
        "simulated",
        "forecast"
      ],
      "title": "DataKind",
      "type": "string"
    },
    "unit": {
      "title": "Unit",
      "type": "string"
    },
    "source": {
      "title": "Source",
      "type": "string"
    },
    "timezone": {
      "default": "UTC",
      "title": "Timezone",
      "type": "string"
    },
    "resolution": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Resolution"
    },
    "provider": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Provider"
    },
    "site_id": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Site Id"
    },
    "asset_id": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Asset Id"
    },
    "time_start": {
      "anyOf": [
        {
          "format": "date-time",
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Time Start"
    },
    "time_end": {
      "anyOf": [
        {
          "format": "date-time",
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Time End"
    },
    "quantity_shape": {
      "anyOf": [
        {
          "enum": [
            "interval",
            "instantaneous",
            "counter"
          ],
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Quantity Shape"
    },
    "original_unit": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Original Unit"
    },
    "field_units": {
      "additionalProperties": {
        "type": "string"
      },
      "title": "Field Units",
      "type": "object"
    },
    "retrieved_at": {
      "format": "date-time",
      "title": "Retrieved At",
      "type": "string"
    },
    "assumptions": {
      "items": {
        "type": "string"
      },
      "title": "Assumptions",
      "type": "array"
    },
    "warnings": {
      "items": {
        "type": "string"
      },
      "title": "Warnings",
      "type": "array"
    },
    "quality": {
      "default": "unknown",
      "title": "Quality",
      "type": "string"
    },
    "provenance": {
      "items": {
        "additionalProperties": true,
        "type": "object"
      },
      "title": "Provenance",
      "type": "array"
    }
  },
  "required": [
    "data",
    "kind",
    "unit",
    "source"
  ],
  "title": "EnergyResult",
  "type": "object"
} as const;
export type EnergyResult = FromSchema<typeof EnergyResultSchema, { keepDefaultedPropertiesOptional: true }>;

export const ToolkitSchema = {
  "additionalProperties": false,
  "properties": {
    "id": {
      "title": "Id",
      "type": "string"
    },
    "name": {
      "title": "Name",
      "type": "string"
    },
    "description": {
      "title": "Description",
      "type": "string"
    },
    "runtime": {
      "enum": [
        "http",
        "python",
        "native",
        "executable",
        "mcp-local",
        "mcp-remote"
      ],
      "title": "Runtime",
      "type": "string"
    },
    "status": {
      "enum": [
        "stable",
        "experimental",
        "requires credentials",
        "unavailable"
      ],
      "title": "Status",
      "type": "string"
    },
    "auth_required": {
      "default": false,
      "title": "Auth Required",
      "type": "boolean"
    },
    "docs_url": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Docs Url"
    },
    "version": {
      "default": "1.0.0",
      "title": "Version",
      "type": "string"
    },
    "categories": {
      "items": {
        "type": "string"
      },
      "title": "Categories",
      "type": "array"
    }
  },
  "required": [
    "id",
    "name",
    "description",
    "runtime",
    "status"
  ],
  "title": "Toolkit",
  "type": "object"
} as const;
export type Toolkit = FromSchema<typeof ToolkitSchema, { keepDefaultedPropertiesOptional: true }>;

export const ToolkitsResponseSchema = {
  "type": "object",
  "properties": {
    "toolkits": {
      "type": "array",
      "items": {
        "additionalProperties": false,
        "properties": {
          "id": {
            "title": "Id",
            "type": "string"
          },
          "name": {
            "title": "Name",
            "type": "string"
          },
          "description": {
            "title": "Description",
            "type": "string"
          },
          "runtime": {
            "enum": [
              "http",
              "python",
              "native",
              "executable",
              "mcp-local",
              "mcp-remote"
            ],
            "title": "Runtime",
            "type": "string"
          },
          "status": {
            "enum": [
              "stable",
              "experimental",
              "requires credentials",
              "unavailable"
            ],
            "title": "Status",
            "type": "string"
          },
          "auth_required": {
            "default": false,
            "title": "Auth Required",
            "type": "boolean"
          },
          "docs_url": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Docs Url"
          },
          "version": {
            "default": "1.0.0",
            "title": "Version",
            "type": "string"
          },
          "categories": {
            "items": {
              "type": "string"
            },
            "title": "Categories",
            "type": "array"
          }
        },
        "required": [
          "id",
          "name",
          "description",
          "runtime",
          "status"
        ],
        "title": "Toolkit",
        "type": "object"
      }
    }
  },
  "required": [
    "toolkits"
  ],
  "additionalProperties": true
} as const;
export type ToolkitsResponse = FromSchema<typeof ToolkitsResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const SessionResponseSchema = {
  "type": "object",
  "properties": {
    "session_id": {
      "type": "string"
    },
    "site_id": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    }
  },
  "required": [
    "session_id",
    "site_id"
  ],
  "additionalProperties": true
} as const;
export type SessionResponse = FromSchema<typeof SessionResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const SearchResponseSchema = {
  "type": "object",
  "properties": {
    "tools": {
      "type": "array",
      "items": {
        "additionalProperties": true,
        "properties": {
          "name": {
            "title": "Name",
            "type": "string"
          },
          "toolkit": {
            "title": "Toolkit",
            "type": "string"
          },
          "resource_scope": {
            "default": "unclassified",
            "enum": [
              "unclassified",
              "operator",
              "public",
              "account",
              "session"
            ],
            "title": "Resource Scope",
            "type": "string"
          },
          "description": {
            "title": "Description",
            "type": "string"
          },
          "input_schema": {
            "additionalProperties": true,
            "title": "Input Schema",
            "type": "object"
          },
          "account_argument_settings": {
            "additionalProperties": {
              "type": "string"
            },
            "title": "Account Argument Settings",
            "type": "object"
          },
          "capabilities": {
            "items": {
              "type": "string"
            },
            "title": "Capabilities",
            "type": "array"
          },
          "actions": {
            "items": {
              "enum": [
                "read-only",
                "calculation",
                "simulation",
                "external-data",
                "configuration-write",
                "physical-control",
                "safety-critical"
              ],
              "title": "Action",
              "type": "string"
            },
            "title": "Actions",
            "type": "array",
            "uniqueItems": true
          },
          "idempotent": {
            "default": true,
            "title": "Idempotent",
            "type": "boolean"
          },
          "version": {
            "default": "1.0.0",
            "title": "Version",
            "type": "string"
          },
          "reviewed": {
            "default": true,
            "title": "Reviewed",
            "type": "boolean"
          },
          "result_kind": {
            "anyOf": [
              {
                "enum": [
                  "metered",
                  "calculated",
                  "estimated",
                  "simulated",
                  "forecast"
                ],
                "title": "DataKind",
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null
          },
          "result_unit": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Result Unit"
          },
          "dependencies": {
            "items": {
              "type": "string"
            },
            "title": "Dependencies",
            "type": "array"
          },
          "connection_available": {
            "type": "boolean"
          }
        },
        "required": [
          "name",
          "toolkit",
          "description",
          "input_schema",
          "capabilities"
        ],
        "title": "Tool",
        "type": "object"
      }
    }
  },
  "required": [
    "tools"
  ],
  "additionalProperties": true
} as const;
export type SearchResponse = FromSchema<typeof SearchResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const ExecutionResponseSchema = {
  "oneOf": [
    {
      "type": "object",
      "properties": {
        "ok": {
          "const": true
        },
        "execution_id": {
          "type": "string"
        },
        "result": {
          "additionalProperties": false,
          "properties": {
            "data": {
              "title": "Data"
            },
            "kind": {
              "enum": [
                "metered",
                "calculated",
                "estimated",
                "simulated",
                "forecast"
              ],
              "title": "DataKind",
              "type": "string"
            },
            "unit": {
              "title": "Unit",
              "type": "string"
            },
            "source": {
              "title": "Source",
              "type": "string"
            },
            "timezone": {
              "default": "UTC",
              "title": "Timezone",
              "type": "string"
            },
            "resolution": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "default": null,
              "title": "Resolution"
            },
            "provider": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "default": null,
              "title": "Provider"
            },
            "site_id": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "default": null,
              "title": "Site Id"
            },
            "asset_id": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "default": null,
              "title": "Asset Id"
            },
            "time_start": {
              "anyOf": [
                {
                  "format": "date-time",
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "default": null,
              "title": "Time Start"
            },
            "time_end": {
              "anyOf": [
                {
                  "format": "date-time",
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "default": null,
              "title": "Time End"
            },
            "quantity_shape": {
              "anyOf": [
                {
                  "enum": [
                    "interval",
                    "instantaneous",
                    "counter"
                  ],
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "default": null,
              "title": "Quantity Shape"
            },
            "original_unit": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "default": null,
              "title": "Original Unit"
            },
            "field_units": {
              "additionalProperties": {
                "type": "string"
              },
              "title": "Field Units",
              "type": "object"
            },
            "retrieved_at": {
              "format": "date-time",
              "title": "Retrieved At",
              "type": "string"
            },
            "assumptions": {
              "items": {
                "type": "string"
              },
              "title": "Assumptions",
              "type": "array"
            },
            "warnings": {
              "items": {
                "type": "string"
              },
              "title": "Warnings",
              "type": "array"
            },
            "quality": {
              "default": "unknown",
              "title": "Quality",
              "type": "string"
            },
            "provenance": {
              "items": {
                "additionalProperties": true,
                "type": "object"
              },
              "title": "Provenance",
              "type": "array"
            }
          },
          "required": [
            "data",
            "kind",
            "unit",
            "source"
          ],
          "title": "EnergyResult",
          "type": "object"
        }
      },
      "required": [
        "ok",
        "execution_id",
        "result"
      ],
      "additionalProperties": true
    },
    {
      "type": "object",
      "properties": {
        "ok": {
          "const": false
        },
        "execution_id": {
          "type": "string"
        },
        "error": {
          "type": "object",
          "properties": {
            "code": {
              "type": "string"
            },
            "message": {
              "type": "string"
            },
            "retryable": {
              "type": "boolean"
            }
          },
          "required": [
            "code",
            "message"
          ],
          "additionalProperties": true
        },
        "resolution": {
          "type": "object",
          "additionalProperties": true
        }
      },
      "required": [
        "ok",
        "error"
      ],
      "additionalProperties": true
    }
  ]
} as const;
export type ExecutionResponse = FromSchema<typeof ExecutionResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const ResolutionResponseSchema = {
  "type": "object",
  "properties": {
    "capability": {
      "type": "string"
    },
    "candidates": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": true
      }
    },
    "selected": {
      "anyOf": [
        {
          "type": "object",
          "additionalProperties": true
        },
        {
          "type": "null"
        }
      ]
    },
    "status": {
      "enum": [
        "resolved",
        "ambiguous",
        "unavailable"
      ]
    },
    "note": {
      "type": "string"
    }
  },
  "required": [
    "capability",
    "candidates",
    "selected",
    "status",
    "note"
  ],
  "additionalProperties": true
} as const;
export type ResolutionResponse = FromSchema<typeof ResolutionResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const ConnectionCreatedResponseSchema = {
  "type": "object",
  "properties": {
    "ok": {
      "const": true
    },
    "account": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "toolkit": {
          "type": "string"
        },
        "site_id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "enabled": {
          "type": "boolean"
        },
        "auth_scheme": {
          "type": "string"
        },
        "display_name": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "verified": {
          "type": "boolean"
        }
      },
      "required": [
        "id",
        "toolkit",
        "site_id",
        "enabled",
        "auth_scheme",
        "state",
        "verified"
      ],
      "additionalProperties": true
    },
    "health": {
      "type": "object",
      "properties": {
        "connection_id": {
          "type": "string"
        },
        "provider": {
          "enum": [
            "octopus",
            "home_assistant"
          ]
        },
        "status": {
          "const": "healthy"
        },
        "checked_at": {
          "type": "string"
        },
        "probe": {
          "const": "provider-read"
        },
        "message": {
          "type": "string"
        }
      },
      "required": [
        "connection_id",
        "provider",
        "status",
        "checked_at",
        "probe",
        "message"
      ],
      "additionalProperties": true
    }
  },
  "required": [
    "ok",
    "account",
    "health"
  ],
  "additionalProperties": true
} as const;
export type ConnectionCreatedResponse = FromSchema<typeof ConnectionCreatedResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const ConnectionVerificationResponseSchema = {
  "type": "object",
  "properties": {
    "ok": {
      "const": true
    },
    "account": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "toolkit": {
          "type": "string"
        },
        "site_id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "enabled": {
          "type": "boolean"
        },
        "auth_scheme": {
          "type": "string"
        },
        "display_name": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "verified": {
          "type": "boolean"
        }
      },
      "required": [
        "id",
        "toolkit",
        "site_id",
        "enabled",
        "auth_scheme",
        "state",
        "verified"
      ],
      "additionalProperties": true
    },
    "health": {
      "type": "object",
      "properties": {
        "connection_id": {
          "type": "string"
        },
        "provider": {
          "enum": [
            "octopus",
            "home_assistant"
          ]
        },
        "status": {
          "enum": [
            "healthy",
            "unhealthy"
          ]
        },
        "checked_at": {
          "type": "string"
        },
        "probe": {
          "const": "provider-read"
        },
        "message": {
          "type": "string"
        }
      },
      "required": [
        "connection_id",
        "provider",
        "status",
        "checked_at",
        "probe",
        "message"
      ],
      "additionalProperties": true
    }
  },
  "required": [
    "ok",
    "account",
    "health"
  ],
  "additionalProperties": true
} as const;
export type ConnectionVerificationResponse = FromSchema<typeof ConnectionVerificationResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const ConnectionDisconnectedResponseSchema = {
  "type": "object",
  "properties": {
    "ok": {
      "const": true
    },
    "account": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "toolkit": {
          "type": "string"
        },
        "site_id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "enabled": {
          "type": "boolean"
        },
        "auth_scheme": {
          "type": "string"
        },
        "display_name": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "verified": {
          "type": "boolean"
        }
      },
      "required": [
        "id",
        "toolkit",
        "site_id",
        "enabled",
        "auth_scheme",
        "state",
        "verified"
      ],
      "additionalProperties": true
    },
    "upstream_revoked": {
      "anyOf": [
        {
          "type": "boolean"
        },
        {
          "type": "null"
        }
      ]
    }
  },
  "required": [
    "ok",
    "account"
  ],
  "additionalProperties": true
} as const;
export type ConnectionDisconnectedResponse = FromSchema<typeof ConnectionDisconnectedResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const ConnectionsResponseSchema = {
  "type": "object",
  "properties": {
    "connections": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "toolkit": {
            "type": "string"
          },
          "site_id": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "enabled": {
            "type": "boolean"
          },
          "auth_scheme": {
            "type": "string"
          },
          "display_name": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "verified": {
            "type": "boolean"
          }
        },
        "required": [
          "id",
          "toolkit",
          "site_id",
          "enabled",
          "auth_scheme",
          "state",
          "verified"
        ],
        "additionalProperties": true
      }
    }
  },
  "required": [
    "connections"
  ],
  "additionalProperties": true
} as const;
export type ConnectionsResponse = FromSchema<typeof ConnectionsResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const ArtifactsResponseSchema = {
  "type": "object",
  "properties": {
    "artifacts": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": true
      }
    }
  },
  "required": [
    "artifacts"
  ],
  "additionalProperties": true
} as const;
export type ArtifactsResponse = FromSchema<typeof ArtifactsResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const SkillsResponseSchema = {
  "type": "object",
  "properties": {
    "skills": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "intent": {
            "type": "string"
          },
          "capabilities": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "sequence": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "supporting_tools": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "pitfalls": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "executable": {
            "type": "boolean"
          },
          "parameters": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          },
          "evidence_required": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "id",
          "intent",
          "capabilities",
          "sequence",
          "pitfalls"
        ],
        "additionalProperties": true
      }
    }
  },
  "required": [
    "skills"
  ],
  "additionalProperties": true
} as const;
export type SkillsResponse = FromSchema<typeof SkillsResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const JobResponseSchema = {
  "oneOf": [
    {
      "type": "object",
      "properties": {
        "ok": {
          "const": true
        }
      },
      "required": [
        "ok"
      ],
      "additionalProperties": true
    },
    {
      "type": "object",
      "properties": {
        "ok": {
          "const": false
        },
        "error": {
          "type": "object",
          "properties": {
            "code": {
              "type": "string"
            },
            "message": {
              "type": "string"
            },
            "retryable": {
              "type": "boolean"
            }
          },
          "required": [
            "code",
            "message"
          ],
          "additionalProperties": true
        }
      },
      "required": [
        "ok",
        "error"
      ],
      "additionalProperties": true
    }
  ]
} as const;
export type JobResponse = FromSchema<typeof JobResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const DeleteSessionResponseSchema = {
  "type": "object",
  "properties": {
    "deleted": {
      "const": true
    },
    "session_id": {
      "type": "string"
    }
  },
  "required": [
    "deleted",
    "session_id"
  ],
  "additionalProperties": true
} as const;
export type DeleteSessionResponse = FromSchema<typeof DeleteSessionResponseSchema, { keepDefaultedPropertiesOptional: true }>;

export const DeleteArtifactResponseSchema = {
  "type": "object",
  "properties": {
    "deleted": {
      "const": true
    },
    "artifact_id": {
      "type": "string"
    }
  },
  "required": [
    "deleted",
    "artifact_id"
  ],
  "additionalProperties": true
} as const;
export type DeleteArtifactResponse = FromSchema<typeof DeleteArtifactResponseSchema, { keepDefaultedPropertiesOptional: true }>;
